version: '3.7'

services:
  web:
    container_name: ecommerce-api-sequelize
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    restart: always
    environment:
      - NODE_ENV=production
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: donaldwu
      POSTGRES_PASSWORD: donaldwu
      POSTGRES_DB: donaldwu